//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egitmenlere_Gore_Kurslar
    {
        public int kursID { get; set; }
        public string kursAdi { get; set; }
        public Nullable<int> egitmenID { get; set; }
        public string egitmenAdi { get; set; }
        public string egitmenSoyadi { get; set; }
    }
}
