//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici_Durumu
    {
        public int userID { get; set; }
        public string yetkiDurumu { get; set; }
        public string userAdi { get; set; }
        public string userSoyadi { get; set; }
    }
}
