//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kurs()
        {
            this.Konu = new HashSet<Konu>();
        }
    
        public int kursID { get; set; }
        public string kursAdi { get; set; }
        public Nullable<double> fiyat { get; set; }
        public Nullable<int> egitmenID { get; set; }
        public Nullable<int> programID { get; set; }
    
        public virtual Egitmen Egitmen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konu> Konu { get; set; }
        public virtual Kurs_Programi Kurs_Programi { get; set; }
    }
}
