//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KURS_PROGRAMIEntities8 : DbContext
    {
        public KURS_PROGRAMIEntities8()
            : base("name=KURS_PROGRAMIEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Egitmen> Egitmen { get; set; }
        public virtual DbSet<Konu> Konu { get; set; }
        public virtual DbSet<Kurs> Kurs { get; set; }
        public virtual DbSet<Kurs_Programi> Kurs_Programi { get; set; }
        public virtual DbSet<Kurs_Programi_Yoneticisi> Kurs_Programi_Yoneticisi { get; set; }
        public virtual DbSet<Kursiyer> Kursiyer { get; set; }
        public virtual DbSet<Puan> Puan { get; set; }
        public virtual DbSet<Sertifika> Sertifika { get; set; }
        public virtual DbSet<Sinav> Sinav { get; set; }
        public virtual DbSet<User_> User_ { get; set; }
        public virtual DbSet<Video> Video { get; set; }
        public virtual DbSet<Yetki> Yetki { get; set; }
        public virtual DbSet<Egitmenlere_Gore_Kurslar> Egitmenlere_Gore_Kurslar { get; set; }
        public virtual DbSet<Konusuna_Gore_Kurslar> Konusuna_Gore_Kurslar { get; set; }
        public virtual DbSet<Kullanici_Durumu> Kullanici_Durumu { get; set; }
        public virtual DbSet<Kurs_Videolari> Kurs_Videolari { get; set; }
        public virtual DbSet<Kursiyerler> Kursiyerler { get; set; }
        public virtual DbSet<Sertifika_Hakki> Sertifika_Hakki { get; set; }
        public virtual DbSet<Sertifikalara_Gore_Kursiyerler> Sertifikalara_Gore_Kursiyerler { get; set; }
        public object KullaniciDurumu { get; internal set; }
    }
}
