//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puan
    {
        public double puan1 { get; set; }
        public Nullable<bool> sertfHakki { get; set; }
        public Nullable<int> sertifikaID { get; set; }
    
        public virtual Sertifika Sertifika { get; set; }
    }
}
