//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_()
        {
            this.Yetki = new HashSet<Yetki>();
        }
    
        public int userID { get; set; }
        public Nullable<int> yoneticiID { get; set; }
        public Nullable<int> egitmenID { get; set; }
        public Nullable<int> kursiyerID { get; set; }
        public string userAdi { get; set; }
        public string userSoyadi { get; set; }
        public string uPassword { get; set; }
        public string uEmail { get; set; }
    
        public virtual Egitmen Egitmen { get; set; }
        public virtual Kurs_Programi_Yoneticisi Kurs_Programi_Yoneticisi { get; set; }
        public virtual Kursiyer Kursiyer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yetki> Yetki { get; set; }
    }
}
